---

- name: Make artifacts subdir
  win_file:
    path: '{{ artifacts_dir }}'
    state: directory
- name: Copy artifacts to testbed
  copy:
    src: '{{ local_artifacts_dir }}'
    dest: '{{ artifacts_dir }}'
- name: Install artifacts
  

  